AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Sample
Resources:
  Words:
    Type: AWS::Serverless::SimpleTable
  UserList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/words
      Handler: GetWordList.handler
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Timeout: 10
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{userId}/words
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref Words