AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Sample
Resources:
  NewWords:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/words
      Handler: GetNewList.handler
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{userId}/words
            Method: get
  UpdateWord:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/words
      Handler: UpdateWord.handler
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{userId}/{word}
            Method: put